In [1]:
from ucimlrepo import fetch_ucirepo
import pandas as pd

horse_colic = fetch_ucirepo(id=47)

X = horse_colic.data.features
y = horse_colic.data.targets

data_horse_colic = pd.concat([X, y], axis=1)

data_horse_colic

,surgery,age,hospital_number,rectal_temperature,pulse,respiratory_rate,temperature_of_extremities,peripheral_pulse,mucous_membranes,capillary_refill_time,...,packed_cell_volume,total_protein,abdominocentesis_appearance,abdominocentesis_total_protein,outcome,lesion_site,lesion_type,lesion_subtype,cp_data,surgical_lesion
0,2.0,1,530101,38.5,66.0,28.0,3.0,3.0,NaN,2.0,...,45.0,8.4,NaN,NaN,2.0,11300,0,0,2,2
1,1.0,1,534817,39.2,88.0,20.0,NaN,NaN,4.0,1.0,...,50.0,85.0,2.0,2.0,3.0,2208,0,0,2,2
2,2.0,1,530334,38.3,40.0,24.0,1.0,1.0,3.0,1.0,...,33.0,6.7,NaN,NaN,1.0,0,0,0,1,2
3,1.0,9,5290409,39.1,164.0,84.0,4.0,1.0,6.0,2.0,...,48.0,7.2,3.0,5.3,2.0,2208,0,0,1,1
4,2.0,1,530255,37.3,104.0,35.0,NaN,NaN,6.0,2.0,...,74.0,7.4,NaN,NaN,2.0,4300,0,0,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
363,2.0,1,529695,38.6,60.0,30.0,1.0,1.0,3.0,1.0,...,40.0,6.0,1.0,NaN,1.0,3205,0,0,2,1
364,2.0,1,528452,37.8,42.0,40.0,1.0,1.0,1.0,1.0,...,36.0,6.2,NaN,NaN,1.0,4124,0,0,2,2
365,1.0,1,534783,38.0,60.0,12.0,1.0,1.0,2.0,1.0,...,44.0,65.0,3.0,2.0,3.0,2209,0,0,2,1
366,2.0,1,528926,38.0,42.0,12.0,3.0,NaN,3.0,1.0,...,37.0,5.8,NaN,NaN,1.0,3111,0,0,2,2
367,2.0,1,530670,37.6,88.0,36.0,3.0,1.0,1.0,1.0,...,44.0,6.0,NaN,NaN,2.0,2112,0,0,2,1

Вывод 1 и 3 столбцов по отдельности

In [2]:
data_horse_colic.iloc[:, 0].head()

0    2.0
1    1.0
2    2.0
3    1.0
4    2.0
Name: surgery, dtype: float64

In [3]:
data_horse_colic.iloc[:, 2]

0       530101
1       534817
2       530334
3      5290409
4       530255
        ...
363     529695
364     528452
365     534783
366     528926
367     530670
Name: hospital_number, Length: 368, dtype: int64

Вывод 1 и 3 столбца вместе

In [4]:
data_horse_colic.iloc[:, [0, 2]]

     surgery  hospital_number
0        2.0           530101
1        1.0           534817
2        2.0           530334
3        1.0          5290409
4        2.0           530255
..       ...              ...
363      2.0           529695
364      2.0           528452
365      1.0           534783
366      2.0           528926
367      2.0           530670

[368 rows x 2 columns]

Вывод первых 10 строк

In [5]:
data_horse_colic.head(10)

,surgery,age,hospital_number,rectal_temperature,pulse,respiratory_rate,temperature_of_extremities,peripheral_pulse,mucous_membranes,capillary_refill_time,...,packed_cell_volume,total_protein,abdominocentesis_appearance,abdominocentesis_total_protein,outcome,lesion_site,lesion_type,lesion_subtype,cp_data,surgical_lesion
0,2.0,1,530101,38.5,66.0,28.0,3.0,3.0,NaN,2.0,...,45.0,8.4,NaN,NaN,2.0,11300,0,0,2,2
1,1.0,1,534817,39.2,88.0,20.0,NaN,NaN,4.0,1.0,...,50.0,85.0,2.0,2.0,3.0,2208,0,0,2,2
2,2.0,1,530334,38.3,40.0,24.0,1.0,1.0,3.0,1.0,...,33.0,6.7,NaN,NaN,1.0,0,0,0,1,2
3,1.0,9,5290409,39.1,164.0,84.0,4.0,1.0,6.0,2.0,...,48.0,7.2,3.0,5.3,2.0,2208,0,0,1,1
4,2.0,1,530255,37.3,104.0,35.0,NaN,NaN,6.0,2.0,...,74.0,7.4,NaN,NaN,2.0,4300,0,0,2,2
5,2.0,1,528355,NaN,NaN,NaN,2.0,1.0,3.0,1.0,...,NaN,NaN,NaN,NaN,1.0,0,0,0,2,2
6,1.0,1,526802,37.9,48.0,16.0,1.0,1.0,1.0,1.0,...,37.0,7.0,NaN,NaN,1.0,3124,0,0,2,1
7,1.0,1,529607,NaN,60.0,NaN,3.0,NaN,NaN,1.0,...,44.0,8.3,NaN,NaN,2.0,2208,0,0,2,1
8,2.0,1,530051,NaN,80.0,36.0,3.0,4.0,3.0,1.0,...,38.0,6.2,NaN,NaN,3.0,3205,0,0,2,1
9,2.0,9,5299629,38.3,90.0,NaN,1.0,NaN,1.0,1.0,...,40.0,6.2,1.0,2.2,1.0,0,0,0,1,2

Вывод 23 случайных строк

In [6]:
data_horse_colic.sample(23)

,surgery,age,hospital_number,rectal_temperature,pulse,respiratory_rate,temperature_of_extremities,peripheral_pulse,mucous_membranes,capillary_refill_time,...,packed_cell_volume,total_protein,abdominocentesis_appearance,abdominocentesis_total_protein,outcome,lesion_site,lesion_type,lesion_subtype,cp_data,surgical_lesion
145,2.0,1,535246,NaN,80.0,32.0,3.0,3.0,2.0,1.0,...,50.0,80.0,NaN,NaN,1.0,0,0,0,2,1
366,2.0,1,528926,38.0,42.0,12.0,3.0,NaN,3.0,1.0,...,37.0,5.8,NaN,NaN,1.0,3111,0,0,2,2
121,1.0,1,534556,38.3,80.0,40.0,NaN,NaN,6.0,2.0,...,67.0,10.2,2.0,1.0,3.0,2208,0,0,2,1
173,1.0,1,529729,NaN,104.0,NaN,3.0,3.0,5.0,2.0,...,69.0,8.6,2.0,3.4,2.0,2207,0,0,1,1
51,1.0,1,527706,37.4,84.0,36.0,1.0,NaN,3.0,2.0,...,NaN,NaN,3.0,NaN,2.0,7209,0,0,1,1
324,1.0,1,530505,38.1,84.0,44.0,4.0,NaN,4.0,2.0,...,60.0,6.8,NaN,5.7,2.0,2209,0,0,1,1
295,1.0,1,533886,NaN,120.0,70.0,4.0,NaN,4.0,2.0,...,55.0,65.0,NaN,NaN,3.0,3205,0,0,2,2
108,1.0,1,533696,38.7,60.0,32.0,4.0,3.0,2.0,2.0,...,53.0,64.0,3.0,2.0,3.0,3205,0,0,2,1
252,1.0,9,5291719,38.8,124.0,36.0,3.0,1.0,2.0,1.0,...,50.0,7.6,3.0,NaN,2.0,2208,0,0,1,1
157,1.0,1,533928,37.8,60.0,24.0,1.0,NaN,3.0,2.0,...,52.0,75.0,NaN,NaN,3.0,2205,0,0,2,1
96,2.0,1,530319,NaN,84.0,36.0,NaN,NaN,3.0,1.0,...,44.0,8.5,NaN,NaN,1.0,3111,0,0,2,1
203,2.0,1,529685,37.2,36.0,9.0,1.0,1.0,1.0,1.0,...,35.0,5.7,NaN,NaN,1.0,31110,0,0,2,2
274,1.0,1,534624,NaN,76.0,NaN,NaN,3.0,NaN,NaN,...,NaN,NaN,NaN,NaN,3.0,11124,0,0,2,1
82,1.0,9,5290759,38.1,100.0,80.0,3.0,1.0,2.0,1.0,...,36.0,5.7,NaN,NaN,1.0,3111,0,0,2,1
209,2.0,1,534478,37.5,44.0,10.0,3.0,1.0,1.0,1.0,...,43.0,51.0,1.0,1.0,1.0,0,0,0,2,2
74,1.0,9,5292929,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,37.0,4.9,NaN,NaN,2.0,11124,0,0,2,1
80,1.0,1,527518,36.4,98.0,35.0,3.0,3.0,4.0,1.0,...,47.0,6.4,3.0,3.6,2.0,2205,0,0,1,1
333,1.0,1,529765,38.2,76.0,NaN,2.0,3.0,2.0,1.0,...,35.0,6.5,2.0,0.9,1.0,3205,0,0,1,1
340,2.0,1,533815,38.0,56.0,44.0,3.0,3.0,3.0,NaN,...,47.0,70.0,2.0,1.0,1.0,0,0,0,2,2
28,1.0,1,5279442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,4300,0,0,2,2
339,2.0,1,533889,38.2,42.0,16.0,1.0,1.0,3.0,1.0,...,35.0,60.0,1.0,1.0,1.0,0,0,0,2,2
358,1.0,1,535337,36.6,48.0,16.0,3.0,1.0,3.0,1.0,...,27.0,56.0,NaN,NaN,3.0,4206,0,0,2,1
100,1.0,1,535364,38.2,40.0,16.0,3.0,3.0,1.0,1.0,...,34.0,66.0,NaN,NaN,1.0,0,0,0,2,2

Вывод статистики

In [7]:
data_horse_colic.describe(include='all')

,surgery,age,hospital_number,rectal_temperature,pulse,respiratory_rate,temperature_of_extremities,peripheral_pulse,mucous_membranes,capillary_refill_time,...,packed_cell_volume,total_protein,abdominocentesis_appearance,abdominocentesis_total_protein,outcome,lesion_site,lesion_type,lesion_subtype,cp_data,surgical_lesion
count,366.000000,368.000000,3.680000e+02,299.000000,342.000000,297.000000,303.000000,285.000000,320.000000,330.000000,...,331.000000,325.000000,174.000000,133.000000,366.000000,368.000000,368.000000,368.000000,368.000000,368.000000
mean,1.415301,1.608696,1.112334e+06,38.134448,70.757310,30.521886,2.356436,1.961404,2.834375,1.303030,...,45.656798,24.771077,2.045977,2.948120,1.527322,3650.834239,96.972826,6.002717,1.663043,1.369565
std,0.493448,2.123985,1.560122e+06,0.711684,28.089867,17.669651,1.041371,1.052454,1.591732,0.473289,...,10.865663,27.704880,0.803289,1.927064,0.731347,5360.219154,640.506258,115.152085,0.473313,0.483344
min,1.000000,1.000000,5.142790e+05,35.400000,30.000000,8.000000,1.000000,1.000000,1.000000,1.000000,...,4.000000,3.300000,1.000000,0.100000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000
25%,1.000000,1.000000,5.289152e+05,37.800000,48.000000,18.000000,1.000000,1.000000,1.000000,1.000000,...,37.250000,6.500000,1.000000,2.000000,1.000000,2111.750000,0.000000,0.000000,1.000000,1.000000
50%,1.000000,1.000000,5.302990e+05,38.100000,60.000000,28.000000,3.000000,1.000000,3.000000,1.000000,...,44.000000,7.500000,2.000000,2.100000,1.000000,3025.000000,0.000000,0.000000,2.000000,1.000000
75%,2.000000,1.000000,5.347275e+05,38.500000,88.000000,36.000000,3.000000,3.000000,4.000000,2.000000,...,52.000000,58.000000,3.000000,3.900000,2.000000,3209.000000,0.000000,0.000000,2.000000,2.000000
max,2.000000,9.000000,5.305629e+06,40.800000,184.000000,96.000000,4.000000,4.000000,6.000000,3.000000,...,75.000000,89.000000,3.000000,10.100000,3.000000,41110.000000,7111.000000,2209.000000,2.000000,2.000000

In [8]:
target_column = y.columns[0]

grouped_by_result = data_horse_colic.groupby(target_column)

for name, group in grouped_by_result:
    print(f"\nРезультат: {name}")
    print(f"Количество строк: {len(group)}")

Результат: 1
Количество строк: 232

Результат: 2
Количество строк: 136

In [9]:
result_groups = data_horse_colic.groupby(target_column)

first_result_name = list(result_groups.groups.keys())[0]

first_group = result_groups.get_group(first_result_name)

first_value = first_group.iloc[0, 0]

filtered_group = first_group[first_group.iloc[:, 0] == first_value]

print(f"Группа: {first_result_name}")
print(f"Значение первого столбца: {first_value}")
print(f"Количество строк: {len(filtered_group)}")

print(filtered_group.head())

Группа: 1
Значение первого столбца: 1.0
Количество строк: 188
    surgery  age  hospital_number  rectal_temperature  pulse  \
3       1.0    9          5290409                39.1  164.0
6       1.0    1           526802                37.9   48.0
7       1.0    1           529607                 NaN   60.0
10      1.0    1           528548                38.1   66.0
14      1.0    1           534917                38.2   76.0

    respiratory_rate  temperature_of_extremities  peripheral_pulse  \
3               84.0                         4.0               1.0
6               16.0                         1.0               1.0
7                NaN                         3.0               NaN
10              12.0                         3.0               3.0
14              28.0                         3.0               1.0

    mucous_membranes  capillary_refill_time  ...  packed_cell_volume  \
3                6.0                    2.0  ...                48.0
6                1.0                    1.0  ...                37.0
7                NaN                    1.0  ...                44.0
10               5.0                    1.0  ...                44.0
14               1.0                    1.0  ...                46.0

    total_protein  abdominocentesis_appearance  \
3             7.2                          3.0
6             7.0                          NaN
7             8.3                          NaN
10            6.0                          2.0
14           81.0                          1.0

    abdominocentesis_total_protein  outcome  lesion_site  lesion_type  \
3                              5.3      2.0         2208            0
6                              NaN      1.0         3124            0
7                              NaN      2.0         2208            0
10                             3.6      1.0         2124            0
14                             2.0      1.0         2112            0

    lesion_subtype  cp_data  surgical_lesion
3                0        1                1
6                0        2                1
7                0        2                1
10               0        1                1
14               0        2                1

[5 rows x 28 columns]